version: 0.1.{build}
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}-{branch}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-{branch}'
environment:
  Configuration: Release
install:
- sh: sudo apt-get install -y doxygen
- sh: sudo apt-get install -y gitversion
nuget:
  account_feed: true
build_script:
- sh: bash ./build/build.sh -cbd
test_script:
- sh: dotnet test test/Jcd.Utilities.Test/Jcd.Utilities.Test.csproj -c Release
artifacts:
- path: ./docs
  name: jcd-utilities-docs
- path: ./packages
  name: jcd-utilities-nupkg