version: 0.1.{build}.0
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-{label}'
environment:
  Configuration: Release
install:
- sh: sudo apt-get install -y doxygen
nuget:
  account_feed: true
  disable_publish_on_pr: true
build_script:
- sh: >-
    set -xe

    chmod u+x ./build/build.sh

    ./build/build.sh -cbd
test_script:
- sh: dotnet test test/Jcd.Utilities.Test/Jcd.Utilities.Test.csproj -c Release
artifacts:
- path: ./docs
  name: jcd-utilities-docs