version: 0.1.{build}
image: Ubuntu
environment:
  Configuration: Release
install:
- sh: sudo apt-get install -y doxygen
nuget:
  account_feed: true
build_script:
- sh: bash ./build/build.sh -bcd
test_script:
- sh: dotnet test test/Jcd.Utilities.Test/Jcd.Utilities.Test.csproj --no-build
artifacts:
- path: ./docs
  name: jcd-utilities-docs
- path: ./packages
  name: jcd-utilities-nupkg